"""add email verification

Revision ID: 00cbe56f7fb0
Revises: bf3c10d388af
Create Date: 2026-09-17 01:28:01.493677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00cbe56f7fb0'
down_revision: Union[str, Sequence[str], None] = 'bf3c10d388af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # Add the column temporarily with a default value
    op.add_column(
        "users",
        sa.Column(
            "email_verified",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )

    # Remove the database-level default.
    # New users will get the value from the SQLAlchemy model.
    op.alter_column(
        "users",
        "email_verified",
        server_default=None,
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verified')
    # ### end Alembic commands ###
