"""add quiz duration

Revision ID: 1dc762fb5864
Revises: 9f360a00edbe
Create Date: 2026-07-26 20:35:26.392359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dc762fb5864'
down_revision: Union[str, Sequence[str], None] = '9f360a00edbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "quiz",
        sa.Column(
            "duration_minutes",
            sa.Integer(),
            nullable=False,
            server_default="30",
        ),
    )

    op.alter_column(
        "quiz",
        "duration_minutes",
        server_default=None,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz', 'duration_minutes')
    # ### end Alembic commands ###
