"""add descriptive assignment pdf fields

Revision ID: 3cb07c28a44a
Revises: bf5e0fb2e579
Create Date: 2026-08-19 18:32:10.577037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cb07c28a44a'
down_revision: Union[str, Sequence[str], None] = 'bf5e0fb2e579'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('descriptive_assignments', sa.Column('assignment_type', sa.String(), nullable=False))
    op.add_column('descriptive_assignments', sa.Column('question_pdf_url', sa.String(), nullable=True))
    op.add_column('descriptive_assignments', sa.Column('question_pdf_name', sa.String(), nullable=True))
    op.add_column('descriptive_submissions', sa.Column('answer_pdf_url', sa.String(), nullable=True))
    op.add_column('descriptive_submissions', sa.Column('answer_pdf_name', sa.String(), nullable=True))
    op.drop_constraint(op.f('descriptive_submissions_token_key'), 'descriptive_submissions', type_='unique')
    op.create_index(op.f('ix_descriptive_submissions_token'), 'descriptive_submissions', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_descriptive_submissions_token'), table_name='descriptive_submissions')
    op.create_unique_constraint(op.f('descriptive_submissions_token_key'), 'descriptive_submissions', ['token'], postgresql_nulls_not_distinct=False)
    op.drop_column('descriptive_submissions', 'answer_pdf_name')
    op.drop_column('descriptive_submissions', 'answer_pdf_url')
    op.drop_column('descriptive_assignments', 'question_pdf_name')
    op.drop_column('descriptive_assignments', 'question_pdf_url')
    op.drop_column('descriptive_assignments', 'assignment_type')
    # ### end Alembic commands ###
