"""add quiz status

Revision ID: 4ed5db21b428
Revises: f3c6fa396b1b
Create Date: 2026-07-24 03:06:02.402573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ed5db21b428'
down_revision: Union[str, Sequence[str], None] = 'f3c6fa396b1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("quiz", sa.Column('status', sa.String(length=20), nullable=False,server_default="Draft",),)
 
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
  
    op.drop_column("quiz", "status")
    # ### end Alembic commands ###
