"""add ai analysis to responses

Revision ID: 53d67612eeeb
Revises: b7c05f2929a0
Create Date: 2026-09-22 17:03:51.902292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53d67612eeeb'
down_revision: Union[str, Sequence[str], None] = 'b7c05f2929a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('responses', sa.Column('ai_analysis', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('responses', 'ai_analysis')
    # ### end Alembic commands ###
