"""Add teacher ownership to quiz

Revision ID: 72a4f193b55a
Revises: 06d00cfa7fb5
Create Date: 2026-07-22 11:38:33.702716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72a4f193b55a'
down_revision: Union[str, Sequence[str], None] = '06d00cfa7fb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz', sa.Column('teacher_id', sa.Integer(), nullable=True))
    op.add_column('quiz', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('quiz', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'quiz', 'teachers', ['teacher_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quiz', type_='foreignkey')
    op.drop_column('quiz', 'updated_at')
    op.drop_column('quiz', 'created_at')
    op.drop_column('quiz', 'teacher_id')
    # ### end Alembic commands ###
