"""add token and tracking fields to quiz assignments

Revision ID: 9f360a00edbe
Revises: b1cdbddfad0e
Create Date: 2026-07-26 17:26:39.870179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f360a00edbe'
down_revision: Union[str, Sequence[str], None] = 'b1cdbddfad0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_assignments', sa.Column('token', sa.String(), nullable=True))
    op.add_column('quiz_assignments', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('quiz_assignments', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('quiz_assignments', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_quiz_assignments_token'), 'quiz_assignments', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quiz_assignments_token'), table_name='quiz_assignments')
    op.drop_column('quiz_assignments', 'expires_at')
    op.drop_column('quiz_assignments', 'completed_at')
    op.drop_column('quiz_assignments', 'started_at')
    op.drop_column('quiz_assignments', 'token')
    # ### end Alembic commands ###
