"""add questions table

Revision ID: b1cdbddfad0e
Revises: 4ed5db21b428
Create Date: 2026-07-24 16:44:50.617212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1cdbddfad0e'
down_revision: Union[str, Sequence[str], None] = '4ed5db21b428'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quiz_assignments_student_email'), table_name='quiz_assignments')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_quiz_assignments_student_email'), 'quiz_assignments', ['student_email'], unique=False)
    # ### end Alembic commands ###
