"""Add time_taken_seconds to response

Revision ID: b51366429e1d
Revises: 1dc762fb5864
Create Date: 2026-07-27 10:47:48.209862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b51366429e1d'
down_revision: Union[str, Sequence[str], None] = '1dc762fb5864'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('responses', sa.Column('time_taken_seconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('responses', 'time_taken_seconds')
    # ### end Alembic commands ###
