"""add topic to questions

Revision ID: b7c05f2929a0
Revises: b97531d0bbab
Create Date: 2026-09-22 15:52:45.737349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7c05f2929a0'
down_revision: Union[str, Sequence[str], None] = 'b97531d0bbab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('topic', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'topic')
    # ### end Alembic commands ###
