"""add quiz assignment start time

Revision ID: b97531d0bbab
Revises: d42cfb359758
Create Date: 2026-09-22 11:19:49.079581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b97531d0bbab'
down_revision: Union[str, Sequence[str], None] = 'd42cfb359758'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_assignments', sa.Column('start_time', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_assignments', 'start_time')
    # ### end Alembic commands ###
