"""add start date time to descriptive assignments

Revision ID: bcafb5280a69
Revises: 53d67612eeeb
Create Date: 2026-09-29 10:36:49.468232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcafb5280a69'
down_revision: Union[str, Sequence[str], None] = '53d67612eeeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('descriptive_assignments', sa.Column('start_date_time', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('descriptive_assignments', 'start_date_time')
    # ### end Alembic commands ###
