"""add descriptive assignment tables

Revision ID: bf5e0fb2e579
Revises: 4a5bef9261b9
Create Date: 2026-08-14 17:43:59.899622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf5e0fb2e579'
down_revision: Union[str, Sequence[str], None] = '4a5bef9261b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('descriptive_answers', sa.Column('ai_marks', sa.Float(), nullable=True))
    op.add_column('descriptive_answers', sa.Column('teacher_marks', sa.Float(), nullable=True))
    op.add_column('descriptive_answers', sa.Column('final_marks', sa.Float(), nullable=True))
    op.add_column('descriptive_answers', sa.Column('teacher_feedback', sa.String(), nullable=True))
    op.drop_column('descriptive_answers', 'marks_awarded')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('descriptive_answers', sa.Column('marks_awarded', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('descriptive_answers', 'teacher_feedback')
    op.drop_column('descriptive_answers', 'final_marks')
    op.drop_column('descriptive_answers', 'teacher_marks')
    op.drop_column('descriptive_answers', 'ai_marks')
    # ### end Alembic commands ###
