"""add quiz assignment randomization data

Revision ID: d42cfb359758
Revises: 00cbe56f7fb0
Create Date: 2026-09-22 07:43:50.826312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd42cfb359758'
down_revision: Union[str, Sequence[str], None] = '00cbe56f7fb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_assignments', sa.Column('randomization_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_assignments', 'randomization_data')
    # ### end Alembic commands ###
