"""modernize quiz assignments

Revision ID: f3c6fa396b1b
Revises: 72a4f193b55a
Create Date: 2026-07-22 12:33:54.608995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3c6fa396b1b'
down_revision: Union[str, Sequence[str], None] = '72a4f193b55a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_assignments', sa.Column('teacher_id', sa.Integer(), nullable=True))
    op.add_column('quiz_assignments', sa.Column('student_id', sa.Integer(), nullable=True))
    op.add_column('quiz_assignments', sa.Column('section_id', sa.Integer(), nullable=True))
    op.add_column('quiz_assignments', sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('quiz_assignments', sa.Column('due_date', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('quiz_assignments', 'quiz_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    
    op.create_foreign_key(
    "fk_quiz_assignments_teacher",
    "quiz_assignments",
    "teachers",
    ["teacher_id"],
    ["id"],
    )

    op.create_foreign_key(
    "fk_quiz_assignments_quiz",
    "quiz_assignments",
    "quiz",
    ["quiz_id"],
    ["id"],
    )

    op.create_foreign_key(
    "fk_quiz_assignments_student",
    "quiz_assignments",
    "students",
    ["student_id"],
    ["id"],
    )

    op.create_foreign_key(
    "fk_quiz_assignments_section",
    "quiz_assignments",
    "sections",
    ["section_id"],
    ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
    "fk_quiz_assignments_section",
    "quiz_assignments",
    type_="foreignkey",
)

    op.drop_constraint(
    "fk_quiz_assignments_student",
    "quiz_assignments",
    type_="foreignkey",
    )

    op.drop_constraint(
    "fk_quiz_assignments_quiz",
    "quiz_assignments",
    type_="foreignkey",
    )

    op.drop_constraint(
    "fk_quiz_assignments_teacher",
    "quiz_assignments",
    type_="foreignkey",
    )
    op.alter_column('quiz_assignments', 'quiz_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('quiz_assignments', 'due_date')
    op.drop_column('quiz_assignments', 'assigned_at')
    op.drop_column('quiz_assignments', 'section_id')
    op.drop_column('quiz_assignments', 'student_id')
    op.drop_column('quiz_assignments', 'teacher_id')
    # ### end Alembic commands ###
